services:
  registry:
    container_name: registry
    image: registry:2.8.3
    ports:
    - 5000:5000
    restart: always
    volumes:
      - ./config/config.yml:/etc/distribution/config.yml:ro
      - ./data:/var/lib/registry:rw
    #environment:
      #- "STANDALONE=true"
      #- "MIRROR_SOURCE=https://registry-1.docker.io"
      #- "MIRROR_SOURCE_INDEX=https://index.docker.io"
      #REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry
      #REGISTRY_STORAGE_DELETE_ENABLED: "true"