services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine3.19-perl
    network_mode: "host"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d/:rw
      - ./log:/var/log/nginx:rw
      - ./docker.qylab.io.key:/etc/ssl/certs/docker.qylab.io.key:ro
      - ./docker.qylab.io.crt:/etc/ssl/certs/docker.qylab.io.crt:ro
    environment:
      - NGINX_PORT=80